[book]
authors = ["Olle Wreede"]
language = "en"
multilingual = false
src = "src"
title = "Game development in Rust with Macroquad"
description = "A game development guide on how to program a shoot 'em up game with the Rust programming language and the Macroquad game library."

[build]
create-missing = false

[rust]
edition = "2021"

[output.html]
default-theme = "macchiato"
preferred-dark-theme = "macchiato"
smart-punctuation = true
git-repository-url = "https://github.com/ollej/macroquad-introduktion"
additional-css = ["./book.css", "./theme/catppuccin.css", "./theme/catppuccin-highlight.css", "./theme/mdbook-admonish.css", "./theme/catppuccin-admonish.css"]
additional-js = ["code-line-highlight.js"]

[output.html.playground]
runnable = false

[output.html.redirect]
"/github.html" = "https://github.com/ollej/macroquad-introduktion/tree/main/my-game"

[output.pdf]
# A4
#paper-width = 8.268
#paper-height = 11.693
# Book
#paper-width = 7.401575
#paper-height = 9.251969
# US Trade
#paper-width = 6
#paper-height = 9
# Crown quarto
paper-width = 7.44
paper-height = 9.68
# Publit book
#paper-width = 7.87
#paper-height = 10.63
print-background = true
scale = 0.7
#margin-top = 1
#margin-bottom = 1
#margin-left = 1
#margin-right = 1
display-header-footer = true
header-template = " "
footer-template = "<p style='font-size:10px; margin-left: 49%'><span class='pageNumber'></span></p>"
static_site_url = "https://mq.agical.se"
theme = "light"

[preprocessor]
[preprocessor.quiz]
cache-answers = false
spellcheck = false

[preprocessor.catppuccin]
assets_version = "2.0.1" # DO NOT EDIT: Managed by `mdbook-catppuccin install`

[preprocessor.admonish]
command = "mdbook-admonish"
assets_version = "3.0.0" # do not edit: managed by `mdbook-admonish install`

